=== matschieu/univ-projects/univ-projects-game/src/main/resources/config/dtd/gameConfiguration.dtd
<!ELEMENT game (localisation, map, cells, hero, characters, items)>

<!-- Name of the language file used -->
<!ELEMENT localisation (#PCDATA)>

<!ELEMENT map (mapClass, param*)>
<!-- Name of the map class used by the game -->
<!ELEMENT mapClass (#PCDATA)>
<!-- Parameters used for the construction of the map -->
<!ELEMENT param (#PCDATA)>

<!-- Field types used by the map -->
<!ELEMENT cells ((cellClass,rate)*)>
<!-- The name of the class that represents this field type. -->
<!ELEMENT cellClass (#PCDATA)>
<!-- Rate used to know the number of this field to add to the map -->
<!ELEMENT rate (#PCDATA)>

<!ELEMENT hero (heroClass, name, energy, strength, strategy, action*)>
<!-- Name of the hero class -->
<!ELEMENT heroClass (#PCDATA)>
<!-- Values used to initialize the hero/characters -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT energy (#PCDATA)>
<!ELEMENT strength (#PCDATA)>
<!ELEMENT strategy (#PCDATA)>
<!-- Names of action classes enable for the hero/characters -->
<!ELEMENT action (#PCDATA)>

<!ELEMENT characters (nb, character*)>
<!-- Number of characters/items on the map -->
<!ELEMENT nb (#PCDATA)>
<!ELEMENT character (characterClass, rate, energy, strength, strategy, action*)>
<!-- Names of characters classes to add on the map -->
<!ELEMENT characterClass (#PCDATA)>

<!ELEMENT items (nb, item*)>
<!ELEMENT item (itemClass,rate)>
<!-- Names of items classes to add on the map -->
<!ELEMENT itemClass (#PCDATA)>

=== matschieu/univ-projects/univ-projects-game/src/main/resources/config/gameConfig1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "./dtd/gameConfiguration.dtd">

<game>

  <localisation>./lang/Francais.xml</localisation>

  <map>
    <mapClass>game.map.GameMap4</mapClass>
    <param>10</param>
    <param>5</param>
  </map>

  <cells>
    <cellClass>game.map.Field</cellClass>
    <rate>25</rate>
    <cellClass>game.map.Wood</cellClass>
    <rate>25</rate>
    <cellClass>game.map.Water</cellClass>
    <rate>25</rate>
    <cellClass>game.map.Mountain</cellClass>
    <rate>25</rate>
  </cells>

  <hero>
    <heroClass>game.characters.Hero</heroClass>
    <name>Mathieu</name>
    <energy>200</energy>
    <strength>100</strength>
    <strategy>game.strategy.HumanStrategy</strategy>
    <action>game.actions.Quit</action>
    <action>game.actions.Rest</action>
    <action>game.actions.Status</action>
    <action>game.actions.View</action>
    <action>game.actions.DisplayMap</action>
    <action>game.actions.Move</action>
    <action>game.actions.PickUp</action>
    <action>game.actions.Use</action>
    <action>game.actions.Interact</action>
    <action>game.actions.Attack</action>
    <action>game.actions.Options</action>
  </hero>

  <characters>

    <nb>15</nb>

    <character>
      <characterClass>game.characters.Monster</characterClass>
      <rate>80</rate>
      <energy>50</energy>
      <strength>40</strength>
      <strategy>game.strategy.RandomStrategy</strategy>
      <action>game.actions.Rest</action>
      <action>game.actions.Move</action>
      <action>game.actions.PickUp</action>
      <action>game.actions.Use</action>
      <action>game.actions.Interact</action>
      <action>game.actions.Attack</action>
    </character>

    <character>
      <characterClass>game.characters.Healer</characterClass>
      <rate>20</rate>
      <energy>200</energy>
      <strength>0</strength>
      <strategy>game.strategy.RandomStrategy</strategy>
    </character>

  </characters>

  <items>

    <nb>25</nb>

    <item>
      <itemClass>game.items.Burger</itemClass>
      <rate>25</rate>
    </item>
    <item>
      <itemClass>game.items.Potion</itemClass>
      <rate>25</rate>
    </item>
    <item>
      <itemClass>game.items.Purse</itemClass>
      <rate>25</rate>
    </item>
    <item>
      <itemClass>game.items.Treasure</itemClass>
      <rate>25</rate>
    </item>

  </items>

</game>
