=== matschieu/univ-projects/univ-projects-gol/src/main/resources/config/dtd/gol_dtd.dtd
<!ELEMENT gol (config, aliveCells)>

<!ELEMENT config (width, height, rate, generation, icons)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT generation (#PCDATA)>
<!ELEMENT icons (#PCDATA)>

<!ELEMENT aliveCells (cell*)>
<!ELEMENT cell (x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

=== matschieu/univ-projects/univ-projects-gol/src/main/resources/config/save.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gol SYSTEM "./dtd/gol_dtd.dtd">

<gol>

	<config>
		<width>15</width>
		<height>15</height>
		<rate>50</rate>
		<generation>5</generation>
		<icons>true</icons>
	</config>

	<aliveCells>
		<cell>
			<x>0</x>
			<y>0</y>
		</cell>
		<cell>
			<x>1</x>
			<y>1</y>
		</cell>
		<cell>
			<x>2</x>
			<y>2</y>
		</cell>
		<cell>
			<x>3</x>
			<y>3</y>
		</cell>
	</aliveCells>

</gol>
