=== matschieu/univ-projects/univ-projects-desks/xml/desks.dtd
<!ELEMENT deskslist (desk*)>

<!ELEMENT desk (id, number, building, room, description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== matschieu/univ-projects/univ-projects-desks/src/main/resources/xml/desks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deskslist SYSTEM "./desks.dtd">

<deskslist>
  <desk>
    <id>3</id>
    <number>SUP14</number>
    <building>SUP</building>
    <room>SUP14</room>
    <description>Amphi</description>
  </desk>
  <desk>
    <id>4</id>
    <number>321</number>
    <building>M3</building>
    <room>321</room>
    <description />
  </desk>
  <desk>
    <id>2</id>
    <number>Amphi turing</number>
    <building>M3</building>
    <room>Amphi turing</room>
    <description />
  </desk>
  <desk>
    <id>5</id>
    <number>A10</number>
    <building>M5</building>
    <room>A10</room>
    <description>Salle informatique en acc√®s libre</description>
  </desk>
</deskslist>
