=== matschieu/univ-projects/univ-projects-desks/xml/reservations.dtd
<!ELEMENT reservationslist (reservation*)>

<!ELEMENT reservation (resid, deskid, managerid, traineeid, startday, startyear, endday, endyear)>
<!ELEMENT resid (#PCDATA)>
<!ELEMENT deskid (#PCDATA)>
<!ELEMENT managerid (#PCDATA)>
<!ELEMENT traineeid (#PCDATA)>
<!ELEMENT startday (#PCDATA)>
<!ELEMENT startyear (#PCDATA)>
<!ELEMENT endday (#PCDATA)>
<!ELEMENT endyear (#PCDATA)>

=== matschieu/univ-projects/univ-projects-desks/src/main/resources/xml/reservations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reservationslist SYSTEM "./reservations.dtd">

<reservationslist>
  <reservation>
    <resid>2</resid>
    <deskid>3</deskid>
    <managerid>2</managerid>
    <traineeid>3</traineeid>
    <startday>1</startday>
    <startyear>2010</startyear>
    <endday>1</endday>
    <endyear>2010</endyear>
  </reservation>
  <reservation>
    <resid>3</resid>
    <deskid>2</deskid>
    <managerid>2</managerid>
    <traineeid>3</traineeid>
    <startday>1</startday>
    <startyear>2010</startyear>
    <endday>1</endday>
    <endyear>2010</endyear>
  </reservation>
  <reservation>
    <resid>5</resid>
    <deskid>4</deskid>
    <managerid>2</managerid>
    <traineeid>3</traineeid>
    <startday>2</startday>
    <startyear>2010</startyear>
    <endday>2</endday>
    <endyear>2010</endyear>
  </reservation>
  <reservation>
    <resid>6</resid>
    <deskid>4</deskid>
    <managerid>2</managerid>
    <traineeid>3</traineeid>
    <startday>4</startday>
    <startyear>2010</startyear>
    <endday>18</endday>
    <endyear>2010</endyear>
  </reservation>
</reservationslist>
